# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.lucaswaldburger.me/
title: Lucas Waldburger
email: lwaldburger@berkeley.edu
author: Lucas Waldburger
description: > # "Lucas Waldburger's Personal Website"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: envelope
    title: email
    url: mailto:lwaldburger@berkeley.edu
  - icon: file-pdf-o
    title: resume
    url: http://www.lucaswaldburger.me/rsc/resume.pdf
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/lucas-waldburger-0b57a29a
  - icon: github
    title: github
    url: https://github.com/lucaswaldburger

